#!/usr/bin/env python3
"""Build lecture-notes/chapters/index.tex: tool map, named results, corpus papers.

Chapter-number-based (\ref to existing labels), no makeindex, no \index markup
in the chapters. Reads main.tex's \include order, so it stays in sync with the
book's chapter sequence. Rerunnable: output is regenerated wholesale.

Usage:  python3 scripts/11_make_index.py
"""
import re
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LN = ROOT / "lecture-notes"

KINDS = {"theorem": "Theorem", "lemma": "Lemma", "proposition": "Proposition",
         "corollary": "Corollary", "definition": "Definition"}
ENV = "|".join(KINDS)


def tex_sort_key(s: str) -> str:
    """Alphabetize on letters only: drop commands, braces, math, punctuation."""
    s = re.sub(r"\\[a-zA-Z]+", "", s)      # \emph, \'e, \pods ...
    s = re.sub(r"[{}$\\]", "", s)          # delimiters
    s = s.lower()
    m = re.search(r"[a-z]", s)
    if m and m.start() > 0:
        s = s[m.start():]                  # sort math-first names by first letter
    return re.sub(r"[^a-z0-9]", "", s) or "zzz"


def main() -> int:
    main_tex = (LN / "main.tex").read_text()
    order = [c for c in re.findall(r"\\include\{chapters/([a-z0-9-]+)\}", main_tex)
             if c != "index"]

    chapters = []  # (slug, title, ch-label)
    for slug in order:
        text = (LN / f"chapters/{slug}.tex").read_text()
        mt = re.search(r"\\chapter\{([^}]*)\}", text)
        ml = re.search(r"\\label\{(ch:[^}]*)\}", text)
        if not mt or not ml:
            print(f"WARNING: {slug}: missing chapter title or ch: label", file=sys.stderr)
            continue
        chapters.append((slug, mt.group(1), ml.group(1)))

    # --- named results: \begin{kind}[Name ...]\label{...}
    results = {}  # display name -> [(kind word, ref label)]
    unmatched = 0
    for slug, _, _ in chapters:
        text = (LN / f"chapters/{slug}.tex").read_text()
        for m in re.finditer(r"\\begin\{(" + ENV + r")\}\[([^\]]*)\]", text):
            kind, name = m.group(1), m.group(2)
            lm = re.search(r"\\label\{((?:thm|lem|prop|cor|def):[^}]*)\}",
                           text[m.end():m.end() + 300])
            if not lm:
                unmatched += 1
                continue
            # drop source attributions: '; Theorem of the paper, ...' and
            # ', Theorem~6.4 of the paper, ...' (kinds in both singular/plural)
            name = re.sub(r"\s*;[\s\S]*$", "", name)
            name = re.sub(r",\s*(?:Theorems?|Lemmas?|Propositions?|Corollaries?|"
                          r"Definitions?|Claims?|Facts?|Observations?)\b[\s\S]*$", "", name)
            if "the paper" in name:  # one-off attribution phrasings
                name = re.sub(r",[^,]*the paper[\s\S]*$", "", name)
            name = name.strip()
            results.setdefault(name, []).append((KINDS[kind], lm.group(1)))

    # --- corpus papers cited per chapter (PODS flagged by a trailing \pods)
    papers = {}  # sigmod26-NNN -> {"ch": [labels], "pods": bool}
    for slug, _, chlab in chapters:
        text = (LN / f"chapters/{slug}.tex").read_text()
        for m in re.finditer(r"sigmod26-\d+", text):
            pid = m.group(0)
            d = papers.setdefault(pid, {"ch": [], "pods": False})
            if chlab not in d["ch"]:
                d["ch"].append(chlab)
            if "\\pods" in text[m.end():m.end() + 15]:
                d["pods"] = True

    # --- titles from the master corpus bib (clean LaTeX, script 09)
    titles = {}
    refs = (LN / "refs.bib").read_text()
    for m in re.finditer(r"@article\{(sigmod26-\d+),(.*?)\}\s*(?=@|\Z)", refs, re.S):
        tm = re.search(r"title\s*=\s*\{(.*?)\}", m.group(2), re.S)
        if tm:
            titles[m.group(1)] = re.sub(r"\s+", " ", tm.group(1)).strip()
    missing = [p for p in papers if p not in titles]
    if missing:
        print(f"WARNING: no title for {missing}", file=sys.stderr)

    # ---------------- emit ----------------
    out = []
    w = out.append
    w("% AUTO-GENERATED by scripts/11_make_index.py -- do not edit by hand.")
    w("% Regenerate with: python3 scripts/11_make_index.py")
    w("\\chapter*{Index}")
    w("\\addcontentsline{toc}{chapter}{Index}")
    w("\\markboth{Index}{Index}")
    w("")
    w("Chapter numbers follow the \\texttt{\\textbackslash ref} labels of the book, so")
    w("every entry below is also a hyperlink. Exemplar papers keep their corpus")
    w("identifier \\texttt{sigmod26-NNN}; PODS'26 exemplars are marked. Full")
    w("references appear in each chapter's bibliography.")
    w("")
    w("\\section*{Tools and chapters}")
    w("\\begin{itemize}")
    for slug, title, lab in chapters:
        # unbreakable space after the em-dash: a wrapped entry breaks BEFORE
        # the dash, never leaving it dangling at line end
        w(f"  \\item \\hyperref[{lab}]{{{title}}} ---~\\mbox{{Chapter~\\ref{{{lab}}}}}")
    w("\\end{itemize}")
    w("")
    w("% columns start on a fresh page: keeps the section heading with its list")
    w("\\clearpage")
    w("\\section*{Named theorems, lemmas, and definitions}")
    w("\\begin{multicols}{2}")
    w("\\RaggedRight")   # narrow columns: no justification squeeze
    w("\\begin{itemize}")
    for name in sorted(results, key=tex_sort_key):
        refs_str = ", ".join(f"\\mbox{{{kw}~\\ref{{{lab}}}}}" for kw, lab in results[name])
        w(f"  \\item {name}, {refs_str}")
    w("\\end{itemize}")
    w("\\end{multicols}")
    w("")
    w("\\section*{Corpus papers used as exemplars}")
    w("\\begin{multicols}{2}")
    w("\\RaggedRight")
    w("\\begin{itemize}")
    def paper_key(pid):
        return tex_sort_key(titles.get(pid, pid))
    for pid in sorted(papers, key=paper_key):
        d = papers[pid]
        chs = ", ".join(f"\\mbox{{Ch.~\\ref{{{c}}}}}" for c in d["ch"])
        pods = " (PODS'26)" if d["pods"] else ""
        w(f"  \\item {titles.get(pid, pid)} \\texttt{{{pid}}}{pods} ---~{chs}")
    w("\\end{itemize}")
    w("\\end{multicols}")
    w("")

    (LN / "chapters" / "index.tex").write_text("\n".join(out))
    print(f"chapters/index.tex: {len(chapters)} chapters, "
          f"{len(results)} result names ({unmatched} envs without label skipped), "
          f"{len(papers)} corpus papers "
          f"({sum(1 for d in papers.values() if d['pods'])} PODS-flagged).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
